config/routes.rb
Rails.application.routes.draw do
get 'sessions/new'
resources :boards
resources :votes
resources :comments
resources :links
resources :users
get '/signup', to: 'users#new'

get '/login', to: 'sessions#new', as: 'login'
post '/login', to: 'sessions#create', as: 'create_session'
get '/logout', to: 'sessions#destroy', as: 'logout'

root 'links#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :links

  def self.select_boards
    all.map { |category| [board.category, board.id] }
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many :votes
  belongs_to :user
  belongs_to :link

  def self.select_comments
    all.map { |comment| [comment.body, comment.id] }
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments
  has_many :votes
  belongs_to :user
  belongs_to :board

  def self.select_links
    all.map { |link| [link.title, link.post, link.id] }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  has_many :comments
  has_many :votes

  def self.select_users
    all.map { |user| [user.email, user.id] }
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :current_user

  include ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if current_user == nil
      redirect_to login_path, alert: "You must be logged in."
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end


  def show
    set_board

  end


  def new
    @board = Board.new
  end


  def edit
    set_board
  end


  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to @board, notice: 'Board was successfully created.'
    else
      render :new
    end
  end


  def update
    set_board
    if @board.update(board_params)
      redirect_to @board, notice: 'Board was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    set_board
    @board.destroy
    redirect_to boards_url, notice: 'Board was successfully destroyed.'
  end

  private
  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:category)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
    set_comment
  end


  def new
    @comment = Comment.new
    @all_users = User.select_users
    @all_links = Link.select_links
  end


  def edit
    set_comment
    @all_users = User.select_users
    @all_links = Link.select_links
  end


  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end


  def update
    set_comment
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    set_comment
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id, :link_id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]


  def index
    # @links_and_votes = Link.all
    @links_and_votes = Link.select('links.id, post, title, sum(number) as "vote_count"')
                           .joins('left join votes on votes.link_id = links.id')
                           .group('links.id')
  end

  def show
    set_link
  end

  def new
    @link = Link.new
    @all_users = User.select_users
    @all_categories = Board.select_categories
  end

  def edit
    set_link
    @all_users = User.select_users
    @all_categories = Board.select_categories
  end


  def create
    @link = Link.new(link_params)

    if @link.save
      redirect_to @link, notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  def update
    set_link
    if @link.update(link_params)
      redirect_to @link, notice: 'Link was successfully updated.'
    else
      render :edit
    end

  end


  def destroy
    set_link
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  private
  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:post, :title, :user_id, :board_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user != nil && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Success'
    else
      flash[:alert] = 'Email or password did not match'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Successfully Logged Out. Goodbye!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  # GET /users/1
  def show
    set_user
  end

  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    set_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    set_user
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    set_user
    @user.destroy (user_params)
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  def index
    @votes = Vote.all
  end


  def show
    set_vote
  end


  def new
    @vote = Vote.new
    @all_users = User.select_users
    @all_links = Link.select_links
    @all_comments = Comment.select_comments
  end


  def edit
    set_vote
    @all_users = User.select_users
    @all_links = Link.select_links
    @all_comments = Comment.select_comments
  end


  def create
    @vote = Vote.new(vote_params)

      if @vote.save
        redirect_to @vote, notice: 'Vote was successfully created.'
      else
        render :new
      end

  end


  def update
    set_vote

      if @vote.update(vote_params)
        redirect_to @vote, notice: 'Vote was successfully updated.'
      else
        render :edit
      end

  end


  def destroy
    set_vote
    @vote.destroy
    redirect_to votes_url, notice: 'Vote was successfully destroyed.'

  end

  private
    def set_vote
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:number,:voter_user_id, :vote_direction, :user_id, :link_id, :comment_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    unless @current_user.nil?
      true
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.category %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @board.category %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :user_id, "User" %><br>
    <%= f.select :user_id, @all_users %>
  </div>
  <div class="field">
    <%= f.label :link_id, "Link" %><br>
    <%= f.select :link_id, @all_links %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>

        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %><br>
<%= link_to 'Log in', login_path %> |
<%= link_to 'Log out', logout_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @comment.user.name %>
</p>

<p>
  <strong>Link</strong>
  <%=  link_to @comment.link.title %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>NAME</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
  <%= csrf_meta_tags %>
</head>
<body>
 <header class='main'>
    <div class="row">
    <div class="col-md-6">
    <h1><%= link_to 'Reddit', root_path %></h1>
    </div>
    <div class="col-md-6; text-center">
    <nav>
      <h5>
      |
      <%= link_to 'Users', users_path %>
      |
      <%= link_to 'Links', links_path %>
      |
      <%= link_to 'Comments', comments_path %>
      |
      <%= link_to 'Boards', boards_path %>
      |
      <%= link_to 'Sign Up', new_user_path %>
      |
      <% if logged_in? %>
        <%= link_to 'Logout', logout_path %>
      <% else %>
        <%= link_to 'Login', login_path %>
      <% end %>
      |
    </h5>
    </nav>
    </div>
    <% if @current_user %>
      <%= "Hello, #{@current_user.email}" %>
    <% end %>
  </header>
  <div class='container'>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, { class: "flash #{name}" }) %>
    <% end %>
    <%= yield %>
  </div>
  <footer>
    <%= params.inspect if Rails.env.development? %>
    Do you want to join daily Reddit?

  </footer>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_field :post %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id, "User" %><br>
    <%= f.select :user_id, @all_users %>
  </div>
  <div class="field">
    <%= f.label :board_id, "Category" %><br>
    <%= f.select :board_id, @all_categories %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<div class="row">
  <h4>
    <div class="col-md-3">Post</div>
    <div class="col-md-1">Title</div>
    <div class="col-md-1">Vote(s)</div>
    <div class="col-md-1">Action</div>
  </h4>
</div>
<% @links_and_votes.each do |link| %>
  <div class="row">
    <div class="col-md-3"><%= link.post %></div>
    <div class="col-md-1"><%= link.title %></div>
    <div class="col-md-1"><div class="text-center"><%= link.vote_count ||= 0 %></div></div>
    <div class="col-md-1">
      <%= link_to 'Show', link %>&nbsp;<%= link_to 'Edit', edit_link_path(link) %>&nbsp;<%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>


<!-- <table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Title</th>
      <th>Vote(s)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links_and_votes.each do |link| %>
      <tr>
        <td><%= link.post %></td>
        <td><%= link.title %></td>
        <td><%= link.vote_count ||= 0 %></td>

        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 -->
<br>

<%= link_to 'New Link', new_link_path %><br>
<%= link_to 'Log in', login_path %> |
<%= link_to 'Log out', logout_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @link.post %>
</p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @link.user.name %>
</p>

<p>
  <strong>Category</strong>
  <%=  link_to @link.board.category %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

   <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Sign up', new_user_path %><br>
<%= link_to 'Log in', login_path %> |
<%= link_to 'Log out', logout_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
     <div class="field">
    <%= f.label :voter_user_id, "Voter" %><br>
    <%= f.select :voter_user_id, @all_users %>
  </div>
   <div class="field">
    <%= f.label :vote_direction, "Vote Direction" %><br>
    <%= f.select :vote_direction, ["up", "down"] %>
  </div>
  <div class="field">
    <%= f.label :link_id, "Link" %><br>
    <%= f.select :link_id, @all_links %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votes</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.number %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @vote.number %>
</p>
<p>
  <strong>Voter:</strong>
  <%= @vote.voter_user_id %>
</p>
<p>
  <strong>Voter_Direction:</strong>
  <%= @vote.vote_direction %>
</p>



<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>

app/views/welcome/index.html.erb
<h2>Welcome to My blog</h2>

<h3>Most Popular Posts</h3>
<ol>
  <%= render partial: 'shared/post_list', locals: { posts: @popular_posts } %>
</ol>

<h3>Categories</h3>
<ul>
  <% @categories.each do |cat| %>
    <%= content_tag(:li, link_to(cat, category_path(cat))) %>
  <% end %>
</ul>